package com.eldoradocardgame.application.util;

public enum NomeNazione {

    AUSTRIA, BELGIO, BULGARIA, CIPRO, CROAZIA, DANIMARCA, ESTONIA, FINLANDIA, FRANCIA, GERMANIA, GRECIA, IRLANDA, ITALIA,
    LETTONIA, LISTUANIA, LUSSEMBURGO, MALTA, PAESI_BASSI, POLONIA, PORTOGALLO, REPUBBLICA_CECA, ROMANIA, SLOVACCHIA,
    SLOVENIA, SPAGNA, SVEZIA, UNGHERIA;
}
